<?php
/**
 * Created by PhpStorm.
 * User: zhangxiao-pc
 * Date: 2016/3/21
 * Time: 15:49
 */

namespace api\controllers;


use common\models\ApiBaseException;
use common\models\ApiErrorDescs;
use common\models\ApiUtils;
use common\models\Escrow;
use common\models\EscrowAccount;
use common\models\MemberPayonline;
use common\models\Members;
use common\models\TimeUtils;
use yii\web\Response;

class EscrowController extends UserBaseController
{
    public function behaviors()
    {
        \Yii::$app->response->format=Response::FORMAT_JSON;
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /*
     * 第三方账户开通
     */
    public function actionRegisterBind(){
        try{
            $request = $_REQUEST;
            $userId = ApiUtils::getIntParam('user_id', $request);
            $timer = new TimeUtils();

            $timer->start('user_third_bind');
            $userBind = EscrowAccount::getUserBindInfo($userId);
            $timer->stop('user_third_bind');

            if(empty($userBind['qddBind'])){
                $userInfo = Members::get($userId);
                $objEsc = new Escrow();
                $qddRegParams = $objEsc->registerAccount($userInfo['user_name']);
                if(empty($qddRegParams)){
                    throw new ApiBaseException(ApiErrorDescs::ERR_QDD_REGISTER_PARAMS_ERR);
                }
                $result = [
                    'code' => ApiErrorDescs::SUCCESS,
                    'message' => 'success',
                    'result' => [
                        'params' => http_build_query($qddRegParams),
                        'request_url' => $objEsc->urlArr['register']
                    ],
                ];
            }else{
                throw new ApiBaseException(ApiErrorDescs::ERR_ALREADY_REGISTER_QDD);
            }
        }catch(ApiBaseException $e){
            $result = [
                'code' => $e->getCode(),
                'message' => $e->getMessage()
            ];
        }
        echo json_encode($result);
        $this->logApi(__CLASS__, __FUNCTION__, $result);
        \Yii::$app->end();
    }
    /*
     * 充值
     */
    public function actionRecharge(){
        try{
            $request = $_REQUEST;
            $userId = ApiUtils::getIntParam('user_id', $request);
            $money = ApiUtils::getFloatParam('money', $request);
            $timer = new TimeUtils();

            if($money <= 0){
                throw new ApiBaseException(ApiErrorDescs::ERR_UNKNOW_ERROR, '充值金额不能小于0元');
            }

            $timer->start('user_third_bind');
            $userEscrow = EscrowAccount::getUserThirdAccout($userId);
            if(empty($userEscrow)){
                throw new ApiBaseException(ApiErrorDescs::ERR_USER_UNBIND_THIRD_PAY);
            }
            $timer->stop('user_third_bind');

            //添加充值记录
            $objMemPay = new MemberPayonline();
            $memPayId = $objMemPay->addRecord($userId, $money);
            $orderId = 'charge' . date('YmdHi') . '_' . $memPayId;

            if(!MemberPayonline::updateAll(['order_no' => $orderId], ['id' => $memPayId])){
                throw new ApiBaseException(ApiErrorDescs::ERR_RECHARGE_ADD_ORDER_FAIL);
            }
            $objEsc = new Escrow();
            $params = $objEsc->expressCharge($userEscrow['qdd_marked'],$orderId, $money, 'uid:' . $userId);
            $url = $objEsc->urlArr['charge'];
            $result = [
                'code' => ApiErrorDescs::SUCCESS,
                'message' => 'success',
                'params' => http_build_query($params),
                'url' => $url,
            ];
        }catch(ApiBaseException $e){
            $result = [
                'code' => $e->getCode(),
                'message' => $e->getMessage()
            ];
        }
        echo json_encode($result);
        $this->logApi(__CLASS__, __FUNCTION__, $result);
        \Yii::$app->end();
    }
}